# Generated by Django 5.0.13 on 2025-11-29 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_autor', models.CharField(max_length=100)),
                ('apellido_autor', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('biografia', models.TextField()),
                ('libros_destacados', models.TextField()),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Autor_Biblioteca',
            },
        ),
        migrations.CreateModel(
            name='Bibliotecario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('cargo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('turno', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Bibliotecario',
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_editorial', models.CharField(max_length=100, unique=True)),
                ('pais_origen', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('sitio_web', models.URLField(max_length=255)),
                ('fecha_fundacion', models.DateField()),
            ],
            options={
                'db_table': 'Editorial_Biblioteca',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('fecha_registro', models.DateField()),
                ('fecha_vencimiento_membresia', models.DateField()),
                ('dni', models.CharField(max_length=20)),
                ('tipo_socio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Socio',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
                ('anio_publicacion', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('num_ejemplares', models.IntegerField()),
                ('fecha_adquisicion', models.DateField()),
                ('estanteria', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editorial', to_field='nombre_editorial')),
            ],
            options={
                'db_table': 'Libro_Biblioteca',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField()),
                ('fecha_devolucion_esperada', models.DateField()),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('estado_prestamo', models.CharField(max_length=50)),
                ('multa_generada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bibliotecario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.bibliotecario')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.socio')),
            ],
            options={
                'db_table': 'Prestamo',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_generacion', models.DateTimeField()),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('estado_pago', models.CharField(max_length=50)),
                ('motivo_multa', models.TextField()),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamo')),
                ('socio_multado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.socio')),
            ],
            options={
                'db_table': 'Multa',
            },
        ),
    ]
